FROM microsoft/aspnetcore-build

COPY . /app
WORKDIR /app

VOLUME /publish-output

RUN dotnet restore \
    && dotnet build -c Release \
    && dotnet publish -c Release -o /publish-output

ENV USER www-data
RUN	chown -R $USER:$USER /app
USER "$USER"
