version: '2'
services:
    mssql:
        image: "microsoft/mssql-server-linux"
        #command: /opt/mssql/bin/sqlservr.sh
        volumes:
            - /mnt/content/Videos/Progz/B/mssql1:/var/opt
        environment:
            - SA_PASSWORD=P@ssw0rd
            - ACCEPT_EULA=Y
    web:
        image: "chaosengine/aspnetcore:latest"
        ports:
            - "8080:5000"
        environment:
            - ConnectionStrings:SqlServer=Server=mssql;Database=test;User Id=test;Password=melexmelex;
        depends_on:
            - mssql
        links:
            - mssql
