// <auto-generated />
using DotnetPlayground.Models;
using InkBall.Module.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
#if INCLUDE_POSTGRES
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#endif
using MySql.EntityFrameworkCore.Metadata;
#if INCLUDE_ORACLE
using Oracle.EntityFrameworkCore.Metadata;
#endif

#nullable disable

namespace DotnetPlayground.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20250205141611_ErrorLog")]
    partial class ErrorLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("DotnetPlayground.SessionCache", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(449);

                b.Property<DateTimeOffset?>("AbsoluteExpiration");

                b.Property<DateTimeOffset>("ExpiresAtTime");

                b.Property<long?>("SlidingExpirationInSeconds");

                b.Property<byte[]>("Value")
                    .IsRequired();

                b.HasKey("Id");

                b.HasIndex("ExpiresAtTime")
                    .HasDatabaseName("Index_ExpiresAtTime");

                b.ToTable("SessionCache");
            });

            modelBuilder.Entity("DotnetPlayground.Models.Blog", b =>
            {
                b.Property<int>("BlogId")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
					.HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
					;

                b.Property<string>("Url")
                    .IsRequired();

                b.HasKey("BlogId");

                b.ToTable("Blog");
            });

            modelBuilder.Entity("DotnetPlayground.Models.DataProtectionKey", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
                    .HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
                    ;

                b.Property<string>("FriendlyName").HasMaxLength(100);

                b.Property<string>("Xml").HasMaxLength(4000);

                b.HasKey("Id");

                b.ToTable("DataProtectionKeys");
            });

            modelBuilder.Entity("DotnetPlayground.Models.GoogleProtectionKey", b =>
            {
                b.Property<string>("Id");

                b.Property<string>("Environment").HasMaxLength(100);

                b.Property<string>("Json")
                    .HasColumnType(BloggingContext.JsonColumnTypeFromProvider(ActiveProvider));

                b.HasKey("Id", "Environment");

                b.ToTable("GoogleProtectionKeys");
            });

            modelBuilder.Entity("DotnetPlayground.Models.HashesInfo", b =>
            {
                b.Property<int>("ID");

                b.Property<string>("Alphabet")
                    .HasColumnType("varchar(100)");

                b.Property<int>("Count");

                b.Property<bool>("IsCalculating");

                b.Property<int>("KeyLength");

                b.HasKey("ID");

                b.ToTable("HashesInfo");
            });

            modelBuilder.Entity("DotnetPlayground.Models.Post", b =>
            {
                b.Property<int>("PostId")
                    .ValueGeneratedOnAdd()
					.HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
					.HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
					;

                b.Property<int>("BlogId");

                b.Property<string>("Content")
                    .IsRequired();

                b.Property<string>("Title")
                    .IsRequired();

                b.HasKey("PostId");

                b.HasIndex("BlogId");

                b.ToTable("Post");
            });

            modelBuilder.Entity("DotnetPlayground.Models.ThinHashes", b =>
            {
                b.Property<string>("Key")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar(20)");

                b.Property<string>("HashMD5")
                    .IsRequired()
                    .HasColumnName("hashMD5")
                    .HasColumnType("char(32)");

                b.Property<string>("HashSHA256")
                    .IsRequired()
                    .HasColumnName("hashSHA256")
                    .HasColumnType("char(64)");

                b.HasKey("Key");

                b.ToTable("Hashes");
            });

            modelBuilder.Entity("IdentitySample.DefaultUI.Data.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("AccessFailedCount");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken();

                b.Property<string>("Email")
                    .HasMaxLength(256);

                b.Property<bool>("EmailConfirmed");

                b.Property<bool>("LockoutEnabled");

                b.Property<DateTimeOffset?>("LockoutEnd");

                b.Property<string>("Name");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256);

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256);

                b.Property<string>("PasswordHash");

                b.Property<string>("PhoneNumber");

                b.Property<bool>("PhoneNumberConfirmed");

                b.Property<string>("SecurityStamp");

                b.Property<bool>("TwoFactorEnabled");

                b.Property<string>("UserName")
                    .HasMaxLength(256);

                b.Property<string>("UserSettingsJSON")
                    .HasColumnName("UserSettings")
                    .HasColumnType(BloggingContext.JsonColumnTypeFromProvider(ActiveProvider));

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter(GamesContext.HasIndexFilterFromProvider(ActiveProvider,
						null, null, null,null, "[NormalizedUserName] IS NOT NULL")
					);

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken();

                b.Property<string>("Name")
                    .HasMaxLength(256);

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256);

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter(GamesContext.HasIndexFilterFromProvider(ActiveProvider,
						null, null, null,null, "[NormalizedName] IS NOT NULL")
					);

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
					.HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
					.HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
					;

                b.Property<string>("ClaimType");

                b.Property<string>("ClaimValue");

                b.Property<string>("RoleId")
                    .IsRequired();

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
					.HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
					.HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
					;

                b.Property<string>("ClaimType");

                b.Property<string>("ClaimValue");

                b.Property<string>("UserId")
                    .IsRequired();

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128);

                b.Property<string>("ProviderKey")
                    .HasMaxLength(128);

                b.Property<string>("ProviderDisplayName");

                b.Property<string>("UserId")
                    .IsRequired();

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId");

                b.Property<string>("RoleId");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128);

                b.Property<string>("Name")
                    .HasMaxLength(128);

                b.Property<string>("Value");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("DotnetPlayground.Models.Post", b =>
            {
                b.HasOne("DotnetPlayground.Models.Blog", "Blog")
                    .WithMany("Post")
                    .HasForeignKey("BlogId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Blog");
            });

            modelBuilder.Entity("ErrorLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("Sqlite:Autoincrement", true)
#if INCLUDE_MYSQL
					.HasAnnotation("MySql:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_SQLSERVER
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_ORACLE
					.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
#endif
#if INCLUDE_POSTGRES
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
#endif
					;

                b.Property<int?>("Column")
                    .HasColumnName("Column");

                b.Property<int?>("HttpStatus")
                    .HasColumnName("HttpStatus");

                b.Property<int?>("Line")
                    .HasColumnName("Line");

                b.Property<string>("Message")
                    .HasMaxLength(4000)
                    .HasColumnName("Message");

                b.Property<string>("Url")
                    .HasMaxLength(1000)
                    .HasColumnName("Url");
                
                b.Property<DateTime>("Created")
					// .ValueGeneratedOnAddOrUpdate()
					.HasColumnType(GamesContext.TimeStampColumnTypeFromProvider(ActiveProvider,
                        "TEXT", "datetime", "timestamp without time zone", "TIMESTAMP(7)", "datetime2"
					))
					.HasDefaultValueSql(GamesContext.TimeStampDefaultValueFromProvider(ActiveProvider,
						"datetime('now','localtime')",
						"CURRENT_TIMESTAMP",
						"CURRENT_TIMESTAMP",
						"CURRENT_TIMESTAMP",
						"GETDATE()"));

				if (ActiveProvider.ToLowerInvariant() == "microsoft.entityframeworkcore.sqlite" || ActiveProvider.ToLowerInvariant() == "sqlite")
                    b.HasKey("Id");
                else
                    b.HasKey("Id", "Created");

                b.ToTable("ErrorLog");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("IdentitySample.DefaultUI.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("IdentitySample.DefaultUI.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("IdentitySample.DefaultUI.Data.ApplicationUser")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("IdentitySample.DefaultUI.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("DotnetPlayground.Models.Blog", b =>
            {
                b.Navigation("Post");
            });
#pragma warning restore 612, 618
        }
    }
}
