version: 2.1
orbs:
  win: circleci/windows@4.1
jobs:
  test:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Update submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --jobs 8
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "DotnetPlayground.Web/DotnetPlayground.Web.csproj" }}
      # - run:
      #     name: "Print Working Directory"
      #     command: dir
      # - run:
      #     name: "Dotnet version"
      #     command: dotnet.exe --info
      - run:
          name: "Install project dependencies"
          command: |
            nvm install lts
            nvm use lts
            dotnet.exe restore
            cd DotnetPlayground.Web
            npm i
            npx playwright install
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
            - C:\Users\circleci\AppData\Local\ms-playwright
          key: dotnet-packages-v1-{{ checksum "DotnetPlayground.Web/DotnetPlayground.Web.csproj" }}
      - run:
          name: "Run Unit and Integration Tests"
          command: |
            $env:DBKind="sqlite" ; $env:ConnectionStrings__Sqlite="Filename=./bin/Debug/net6.0/Blogging.db"
            dotnet.exe test -v n --results-directory:"C:\Users\circleci\project\test_coverage" --collect:"Code Coverage" --logger "trx"
      - run:
          name: "End-2-End Playwright browser tests"
          command: |
            cd DotnetPlayground.Web
            $env:DBKind="sqlite" ; $env:ConnectionStrings__Sqlite="Filename=./bin/Debug/Blogging.db"
            
            npx playwright test
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
      - store_artifacts:
          path: DotnetPlayground.Web\e2e\playwright-report
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              $env:Path += ";$HOME\.dotnet\tools"
              trx2junit C:\Users\circleci\project\test_coverage\*.trx
      - store_test_results:
          path: C:\Users\circleci\project\test_coverage\
  build:
    description: Build application with Release configuration
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Update submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --jobs 8
      - run:
          name: Install dependencies
          command: |
            nvm install lts
            nvm use lts
            node --version
            npm --version
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe publish -c Release --self-contained -r win10-x64 DotnetPlayground.Web
workflows:
  test_and_build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - dev
                - circleci-project-setup
      - build:
          filters:
            branches:
              only:
                - master
                - dev
                - circleci-project-setup
          requires:
            - test