name: .NET Core

on:
  push:
    branches: 
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # 'recursive' 'true' or 'false'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      env:
        DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
      run: dotnet build --configuration Release
    - name: Test with dotnet
      env:
        DBKind: "sqlite"
        ConnectionStrings__Sqlite: "Filename=./bin/Debug/net8.0/Blogging.db"
        DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
      run: dotnet test -v m --configuration Debug
