name: Trivy scan
on:
  push:
    branches: [ master, dev ]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true # 'recursive' 'true' or 'false'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.alpine
          load: true
          tags: docker.io/chaosengine/dotnetplayground:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/chaosengine/dotnetplayground:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
