name: Trivy scan
on:
  push:
    branches: [ master, dev ]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # 'recursive' 'true' or 'false'

      - name: Build an image from Dockerfile
        run: |
          DOCKER_BUILDKIT=1 docker build -t docker.io/chaosengine/dotnetplayground:${{ github.sha }} -f Dockerfile.alpine .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/chaosengine/dotnetplayground:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
